#!/usr/bin/bash
# use: git config core.hooksPath .gitHooks

# availabilty of python
py=$(which py || which python || which python3)
if [[ -z $py ]]
then
  echo "No python found"
  exit 0
fi

# go to the root of the git repo
cd $(git rev-parse --show-toplevel)

# path to sompy python scripts
sompy=$(pwd)/submodules/sompy/somutil

txts=()

for file in $(git diff-index --cached --name-only HEAD); do
  if [ -f $file ]; then txts+=($file); fi
done

echo txt: ${#txts[@]}
done=$($py $sompy/cleanTxt.py -le ${txts[@]})

for file in $done; do git add $file; done
