#!/usr/bin/bash
# use: git config core.hooksPath .gitHooks

# availabilty of python
py=$(which py || which python || which python3)
if [[ -z $py ]]
then
  echo "No python found"
  exit 0
fi

# go to the root of the git repo
cd $(git rev-parse --show-toplevel)

# path to sompy python scripts
sompy=$(pwd)/submodules/sompy/somutil

all=()

for file in $(git diff-index --cached --name-only HEAD); do
  if [ -f $file ]; then all+=($file); fi
done

echo all: ${#all[@]}
$py $sompy/cleanTxt.py -l ${all[@]}

for file in ${all[@]}; do git add $file; done
